### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by wujysh** [DHUers/rigidoj#15]
- Solution list: 
  - [x] show problem title, add memory column
  - [x] change time format
  - [x] color the result,  highlight `Accepted`
- Ranking:
  - [x] rename column
  - [x] color the status `First to solve problem` `Solved problem` `Attempted problem` `Pending judgement`
- [x] [BUG] Submit, go to other page, then go back, submit, the source is blank in post form
- [x] Only validate time when create contest
- [x] Forbidden submit after contest
- [x] New Post & Edit Help

**Comment by fantasticfears** [comment]
> [BUG] Submit, go to other page, then go back, submit, the source is blank in post form
Can't repro here

**Comment by wujysh** [comment]
- [ ] Contest sidebar: `Problem list` is ambiguous
- [ ] [BUG] Doesn't update problem ac% on problem list page
- [ ] [BUG] In solution report, source code is parsed as HTML label
- [ ] [BUG] Submit, go to other page, then go back, submit, the source is blank in post form (Can still be reproduced here!)

**Comment by wujysh** [comment]
- [ ] problem list: ac% =`NaN% ` when no submit
- [ ] need to provide more information (class, studentID) when register
- [ ] show user's class on ranking, or the admin can choose whether to show username or real name?
- [ ] solution report: no line breaks (all in one line...)

**Comment by fantasticfears** [comment]
> click solution result should mark it read and redirect to solution list page

Impossible to find one.

**Comment by wujysh** [comment]
- [ ] AC% is still wrong!
- [ ] notification is broken!

**Comment by fantasticfears** [comment]
> provide ranking & submit records links on contest list page

The whole box is clickable. Would be strange to add the link

**Comment by wujysh** [comment]
- [ ] Can not search user `http://acm.dhu.edu.cn/new/admin/groups/123`
- [ ] Should use english name as param `http://acm.dhu.edu.cn/new/admin/groups`

**Comment by wujysh** [comment]
- [ ] Problem(new/edit) Remote proxy vendor, lack of tip
- [ ] Group: search when add users

**Comment by wujysh** [comment]
- [ ] Post is broken!
```
I, [2015-03-27T06:57:38.573701 #98]  INFO -- : Started GET "/new/posts" for 222.204.211.2 at 2015-03-27 06:57:38 +0000
I, [2015-03-27T06:57:38.575177 #98]  INFO -- : Processing by PostsController#index as HTML
I, [2015-03-27T06:57:38.601171 #98]  INFO -- :   Rendered posts/index.html.haml within layouts/application (23.3ms)
I, [2015-03-27T06:57:38.601460 #98]  INFO -- : Completed 500 Internal Server Error in 26ms (ActiveRecord: 3.4ms)
F, [2015-03-27T06:57:38.603033 #98] FATAL -- :
ActionView::Template::Error (undefined method `user' for nil:NilClass):
     9:     .list-group.post-list
    10:       - @posts.each do |p|
    11:         .list-group-item.post-item
    12:           .avatar= attachment_image_tag p.comments.first.user, :avatar, alt: p.comments.first.user.username, fallback: 'avatar.jpg'
    13:           .content
    14:             .list-group-item-heading= link_to p.title, post_path(p)
    15:             .list-group-item-text
  app/views/posts/index.html.haml:12:in `block in _app_views_posts_index_html_haml___3950780715861677408_70247732732040'
  app/views/posts/index.html.haml:10:in `_app_views_posts_index_html_haml___3950780715861677408_70247732732040'
  config/initializers/silence_logger.rb:22:in `call'
  lib/middleware/unicorn_oobgc.rb:80:in `process_client'
```
